auditbeat.modules:
- module: auditd
  failure_mode: silent
  include_raw_message: false
  include_warnings: false
  audit_rule_files: [ '/etc/auditbeat/audit.rules.d/*.rules' ]
# - module: system
#   datasets:
#     - host    # General host information, e.g. uptime, IPs
#     - login   # User logins, logouts, and system boots.
#     - package # Installed, updated, and removed packages
#     - process # Started and stopped processes
#     - socket  # Opened and closed sockets
#     - user    # User information
#   # How often datasets send state updates with the
#   # current state of the system (e.g. all currently
#   # running processes, all open sockets).
#   state.period: 12h
#   user.detect_password_changes: true
#   login.wtmp_file_pattern: /var/log/wtmp*
#   login.btmp_file_pattern: /var/log/btmp*
output:
  logstash:
    enabled: true
    hosts:
      - '$LOGSTASH_HOST:5044'
      - '127.0.0.1:5044'
    worker: 1
    bulk_max_size: 2048
    compression_level: 3
    index: auditbeat