filebeat:
  inputs:
    -
      paths:
        - '/var/log/audit/*.log'
      input_type: log
      fields:
        log_type: TYPE_AUDIT
      fields_under_root: true
    -
      paths:
        - '/var/log/mysql/slog.log'
      input_type: log
      fields:
        log_type: TYPE_PARSED_SLOG
      fields_under_root: true
    -
      paths:
        - '/home/*/.bash_history'
      input_type: log
      fields:
        log_type: TYPE_BASH
      fields_under_root: true
    -
      paths:
        - '/var/log/http/inbound.log'
      input_type: log
      fields:
        log_type: TYPE_HTTP
      fields_under_root: true
    -
      paths:
        - '/var/log/bash/history.log'
      input_type: log
      fields:
        log_type: TYPE_BASH_CENTRALIZED
      fields_under_root: true
  # registry_file: /var/lib/filebeat/registry
output:
  logstash:
    hosts:
      - 'localhost:5044'
    worker: 1
    bulk_max_size: 2048
    compression_level: 3
    index: filebeat
shipper: null
logging:
  files:
    rotateeverybytes: 10485760
