packetbeat.interfaces.device: any
packetbeat.flows:
      timeout: 30s
    period: 10s
packetbeat.protocols:
- type: mysql
    enabled: true
      ports: [3306]
      send_request: true
      send_response: true
      transaction_timeout: 15s                                      
output.logstash:
    enabled: true
    hosts: ["localhost:5044"]
    worker: 1
    compression_level: 3
      index: 'packetbeat'         
      bulk_max_size: 2048
logging.to_files: true
logging.files:
  rotateeverybytes: 10485760
