packetbeat.interfaces.device: lo
packetbeat.flows:
  enabled: false
  timeout: 30s
  period: -1s
packetbeat.protocols.mysql:
  enabled: true
  ports: [3306]
  send_request: true
  send_response: true
  transaction_timeout: 15s
  fields:
    log_type: TYPE_SQL_RESPONSE
  fields_under_root: true
packetbeat.processors:
- add_fields:
    target: ''
    fields:
      log_type: TYPE_SQL_RESPONSE
queue.mem:
  events: 4096
  flush.min_events: 0
  flush.timeout: 0s
# output.file:
#   path: /var/log/mysql
#   filename: responses.log
#   permissions: 0755
# output.redis:
#   hosts: ["127.0.0.1:6379"]
#   key: "nethive-sqlpacket"
#   db: 0
#   timeout: 10
output.logstash:
  hosts: 127.0.0.1:5044
# output.elasticsearch:
#   hosts: ["127.0.0.1:5129"]
logging.to_files: true
logging.files:
  rotateeverybytes: 10485760
